# Generated by Django 4.2.11 on 2024-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
